$font = Roboto
$symbols = Symbols Nerd Font

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
}

background {
    path = screenshot
    blur_passes = 3
    blur_size = 12
}

label {
    monitor =
    text = 
    font_size = 32
    font_family = $symbols
    position = 0, -7%
    valign = top
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    font_size = 20
    font_family = $font
    position = 0, -13%
    valign = top
}

label {
    monitor =
    text = $TIME
    font_size = 96
    font_family = $font
    position = 0, -15%
    valign = top
}


label {
    monitor =
    text = $DESC
    font_size = 14
    font_family = $font
    position = 0, 8%
    valign = bottom
}

input-field {
    monitor =
    size = 10%, 2%
    dots_center = false
    font_family = $font
    fade_on_empty = false
    placeholder_text = Podaj hasło
    fail_text = Niepoprawne hasło
    dots_spacing = 0.33
    valign = bottom
    position = 0, 5%
}
