set-option -g renumber-windows on
set-option -g set-titles on
set-option -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}"
set-option -g status-style "bg=#{?client_prefix,yellow,green},fg=black"
set-option -g focus-events on
set-option -g destroy-unattached keep-group
set-window-option -g mode-keys vi
set-option -sga command-alias "new-window-in-cwd=new-window -c '#{pane_current_path}'"
set-option -sga command-alias "split-vertically-in-cwd=split-window -v -c '#{pane_current_path}'"
set-option -sga command-alias "split-horizontally-in-cwd=split-window -h -c '#{pane_current_path}'"
set-hook -g session-created "select-window -t :-1"
bind-key -N "Create a new window in the current path" c new-window-in-cwd
bind-key -N "Create a new vertical pane in the current path" \" split-vertically-in-cwd
bind-key -N "Create a new horizontal pane in the current path" % split-horizontally-in-cwd
